---
title: "Arbeidskrav-2"
author: "Kristoffer Solum"
date: "28 9 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
  

library(readxl)
Data <- read_excel("Data.xlsx",na = "NA")

dat <- Data %>%
  select(Subject, Tid, lac.75:lac.250) %>%
  pivot_longer(names_to = "watt",
               values_to = "laktat",
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.75:lac.250) %>%

  
   filter(Subject == 1,
         Tid == "pre",
         !is.na(laktat)) %>% # Remove NA values #kan ta bort filter?
  print()


dat %>%
  ggplot(aes(watt, laktat)) + geom_point() +
  
  geom_smooth(method = "lm", se = FALSE, 
              formula = y ~ poly(x, 3)) # kan ta bort?

# Fit the model
model <- lm(laktat ~ watt + I(watt^2) + I(watt^3), data = dat)

new_data <- data.frame(watt = seq(from = 75, to = 250, by = 0.1)) # lagde tabellen fra 75- 250w slik at det skal bli mulig å sammenligne mellom solum og vetle

new_data$pred <- predict(model, newdata = new_data)

new_data$distance <- abs(new_data$pred - 4)



new_data %>%
  filter(distance == min(distance)) %>% # watt ved 4mmol <3
  print()



new_data %>%
  ggplot(aes(watt, pred)) + geom_point()

summary(model) # kan ta bort?

predict(model) # kan ta bort?
  
```


```{r}
lt <- function(data)  { 
  
  m <- lm(laktat ~ watt + I(watt^2) + I(watt^3), data = data)
  
  new_data <- data.frame(watt = seq(from = min(data$watt), to = max(data$watt), by = 0.01))
  
  new_data$pred <-predict(m, newdata = new_data)
  
  new_data$watt.4mmol <- abs(new_data$pred - 4)
  
  new_data$watt.2mmol <- abs(new_data$pred - 2)
  
  
  results <- data.frame(watt.4mmol = new_data[which.min(new_data$watt.4mmol),1]) %>%
  
  data.frame(watt.2mmol = new_data[which.min(new_data$watt.2mmol),1])
  
  return(results)

 # figur som viser snitt av solum og vetle?
  
  
  

  
  }

lt(dat)

```


```{r}

library(tidyverse)

dat <- Data %>%
  select(Subject, Tid, lac.75:lac.250) %>%
  pivot_longer(names_to = "watt",
               values_to = "laktat",
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.75:lac.250) %>%
  
  filter(!is.na(laktat)) %>%
  
  group_by(Tid, Subject) %>%
  
  mutate(n = n()) %>%
  filter(n >= 4) %>%
  
  group_modify(~ lt(.)) %>% # fasit tabell
  print()




```

```{r}

lac1 <- dat %>%
  group_by(Subject) %>%
  mutate(n = n()) %>%
  filter(n == 2) %>%
  pivot_wider(names_from = Tid, values_from = c(watt.4mmol,watt.2mmol)) %>%
  print()

TE4 <- lac1 %>%
  mutate(diff = watt.4mmol_post - watt.4mmol_pre) %>%
  ungroup() %>%
  
  summarise(s = sd(diff, na.rm = TRUE), 
            m = mean(c(watt.4mmol_post, watt.4mmol_pre)), 
            te = s / sqrt(2), 1,
            cv = 100 * (te / m), 1,
            L = qt(0.975, 4) * s) %>%
  print()


TE2 <- lac1 %>%
  mutate(diff = watt.2mmol_post - watt.2mmol_pre) %>%
  ungroup() %>%
  
  summarise(s = sd(diff, na.rm = TRUE), 
            m = mean(c(watt.2mmol_post, watt.2mmol_pre)), 
            te = s / sqrt(2), 1,
            cv = 100 * (te / m), 1,
            L = qt(0.975, 4) * s) %>%
  print()




```



```{r}
Data2 <- read_excel("Data2.xlsx",na = "NA") %>%
  mutate(diff = post - pre) %>%
  ungroup() %>%
  summarise(s = sd(diff, na.rm = TRUE),
            te = s / sqrt(2),
            m = mean(c(pre, post)),
            cv = (te / m) * 100) %>%
  print()


cv <- round(Data2$cv, 2)

Standardavik <- round(Data2$s, 2)


```

Standardfeilen i studien var `r cv` %.

Standardaviket i studien var `r Standardavik` 
